name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check econgym tests
      - name: Type check
        run: |
          mypy econgym
      - name: Test
        run: |
          pytest -q

name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and deps
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,plot]
      - name: Lint (ruff)
        run: |
          python -m ruff --version || pip install ruff
          ruff check econgym examples tests
      - name: Type-check (mypy)
        run: |
          pip install mypy
          mypy econgym || true
      - name: Run tests
        run: |
          pytest -q


